const copy = {
  en: {
    app_name: 'AI Notes',
    tagline: 'Study smarter, together',
    dashboard: 'Dashboard',
    my_notes: 'My Notes',
    summary: 'Summary',
    quiz: 'Quiz',
    groups: 'Groups',
    settings: 'Settings',
    sign_out: 'Sign out',
    workspace: 'Workspace',
    default_study_language: 'Default study language',
    loading_workspace: 'Loading your workspace...',
    focus_mode: 'Focus mode',
    focus_mode_copy: 'Summaries, quizzes, speech and live collaboration are all connected to your backend now.',
    ready_to_study: 'Ready to study',
    student: 'Student',
    welcome_back: 'Welcome back',
    create_your_account: 'Create your account',
    sign_in_copy: 'Sign in to your workspace and pick up where you left off.',
    signup_copy: 'Set up your study workspace and start using the backend features.',
    full_name: 'Full name',
    email: 'Email',
    password: 'Password',
    please_wait: 'Please wait...',
    log_in: 'Log in',
    create_account: 'Create account',
    loading: 'Loading...',
    create_note: 'Create note',
    create_a_note: 'Create a note',
    note_name: 'Note name',
    name_your_note: 'Name your note',
    creating: 'Creating...',
    cancel: 'Cancel',
    content: 'Content',
    write_your_study_notes_here: 'Write your study notes here...',
    import_note: 'Import note',
    import_note_copy: 'Paste text or upload a `.txt`, `.pdf`, or `.docx` file.',
    optional_title: 'Optional title',
    paste_typed_notes_here: 'Paste typed notes here...',
    importing: 'Importing...',
    import_into_notes: 'Import into notes',
    no_date: 'No date',
    create_a_new_note: 'Create a new note',
    create_note_tile_copy: 'Start a fresh idea right here. Your next note always stays within reach.',
    workspace_overview: 'Workspace overview',
    dashboard_hero: 'Build notes once, then translate, summarize, quiz, speak, and collaborate from the same source.',
    new_note: 'New note',
    open_group_room: 'Open group room',
    habit_tracker: 'Habit tracker',
    your_momentum: 'Your momentum',
    day_streak: 'day streak',
    logins: 'Logins',
    times_you_have_shown_up: 'Times you have shown up',
    streak: 'Streak',
    consecutive_active_days: 'Consecutive active days',
    recent_login_days: 'Recent login days',
    login_rhythm_empty: 'Your login rhythm will start showing up here after your next sign-in.',
    inspiration: 'Inspiration',
    recent_notes: 'Recent notes',
    recent_notes_copy: 'Open a note to edit, study, or share it.',
    view_all: 'View all',
    loading_notes: 'Loading notes...',
    loading_note: 'Loading note...',
    manage_notes_copy: 'Manage imported files, typed notes, and study material in one place.',
    delete_selected: 'Delete selected',
    select_notes: 'Select notes',
    done: 'Done',
    move_to_folder: 'Move to folder',
    move_to_notes: 'Move to notes',
    folders: 'Folders',
    all_notes: 'All notes',
    folder_manage: 'Manage folders',
    new_folder_name: 'New folder name',
    create_folder: 'Create folder',
    open: 'Open',
    move_selected_here: 'Move selected here',
    delete_folder: 'Delete folder',
    no_folders_yet: 'No folders yet. Create one to organize notes separately from your main notes list.',
    edit_your_note: 'Edit your note, then open study mode or quiz mode.',
    untitled_note: 'Untitled Note',
    edit_note_title: 'Edit note title',
    save_note: 'Save note',
    saving: 'Saving...',
    more_note_actions: 'More note actions',
    delete: 'Delete',
    study_mode: 'Study Mode',
    study_mode_copy: 'Generate summaries, translations, and audio playback from your note.',
    generate: 'Generate',
    translation: 'Translation',
    translate: 'Translate',
    no_translation_yet: 'No translation yet.',
    speech_playback: 'Speech playback',
    speech_playback_copy: 'Generate audio for the note using your selected mood and voice.',
    female: 'Female',
    male: 'Male',
    default_voice: 'Default voice',
    generate_note_audio: 'Generate note audio',
    audio_ready: 'Audio ready to play.',
    play: 'Play',
    pause: 'Pause',
    open_audio: 'Open audio',
    no_summary_yet: 'No summary yet. Generate one from this note.',
    quiz_copy: 'Generate and revisit quizzes from your notes in one focused workspace.',
    quiz_mode_copy: 'Generate questions from your note and optionally hear them aloud.',
    generate_quiz: 'Generate quiz',
    quiz_from: 'Quiz from',
    questions: 'questions',
    no_quizzes_yet: 'No quizzes yet. Use the plus button to choose a note and generate one here.',
    generate_a_quiz: 'Generate a quiz',
    show_all_quizzes: 'Show all quizzes',
    open_source_note: 'Open source note',
    no_notes_found: 'No notes found in this section yet.',
    quiz_detail_missing: 'This quiz is not available in your local quiz library yet. Return to the Quiz tab and generate or reopen it there.',
    back_to_quizzes: 'Back to quizzes',
    answer_revealed: 'Answer revealed',
    correct_answer: 'Correct answer',
    reveal: 'Reveal',
    play_question: 'Play question',
    play_explanation: 'Play explanation',
    groups_copy: 'Create shared note rooms and collaborate live.',
    group_name: 'Group name',
    socket_status: 'Socket status',
    live_editor: 'Live editor',
    live_editor_placeholder: 'Type a live group note here, then send it to connected members.',
    send_live_note: 'Send live note',
    clear: 'Clear',
    members: 'Members',
    live_cursors: 'Live cursors',
    live_event_feed: 'Live event feed',
    settings_copy: 'Manage your default language, voice, and profile preferences.',
    preferred_voice: 'Preferred voice',
    use_app_default_voice: 'Use app default voice',
    ui_theme: 'UI theme',
    system: 'system',
    light: 'light',
    dark: 'dark',
    save_settings: 'Save settings',
    summary_copy: 'Keep your summarized notes in one calm workspace so they are always easy to revisit.',
    summarize_a_note: 'Summarize a note',
    show_all_summaries: 'Show all summaries',
    summarized_from: 'Summarized from',
    no_summaries_yet: 'No summaries yet. Use the plus button to pick a note and summarize it here.',
    pick_or_create_summary: 'Pick or create a summary to see the full summarized note here.',
    already_summarized: 'Already summarized',
  },
  es: {
    app_name: 'AI Notes',
    tagline: 'Estudia mejor, en conjunto',
    dashboard: 'Panel',
    my_notes: 'Mis notas',
    summary: 'Resumen',
    quiz: 'Cuestionario',
    groups: 'Grupos',
    settings: 'Configuración',
    sign_out: 'Cerrar sesión',
    workspace: 'Espacio de trabajo',
    default_study_language: 'Idioma de estudio predeterminado',
    loading_workspace: 'Cargando tu espacio de trabajo...',
    focus_mode: 'Modo de enfoque',
    focus_mode_copy: 'Los resúmenes, cuestionarios, audio y colaboración en vivo ya están conectados a tu backend.',
    ready_to_study: 'Listo para estudiar',
    student: 'Estudiante',
    full_name: 'Nombre completo',
    email: 'Correo electrónico',
    password: 'Contraseña',
    loading: 'Cargando...',
    create_note: 'Crear nota',
    create_a_note: 'Crear una nota',
    note_name: 'Nombre de la nota',
    name_your_note: 'Nombra tu nota',
    creating: 'Creando...',
    cancel: 'Cancelar',
    content: 'Contenido',
    write_your_study_notes_here: 'Escribe aquí tus notas de estudio...',
    import_note: 'Importar nota',
    import_note_copy: 'Pega texto o sube un archivo `.txt`, `.pdf` o `.docx`.',
    optional_title: 'Título opcional',
    paste_typed_notes_here: 'Pega aquí las notas escritas...',
    importing: 'Importando...',
    import_into_notes: 'Importar a notas',
    create_a_new_note: 'Crear una nota nueva',
    create_note_tile_copy: 'Empieza una idea nueva aquí mismo. Tu próxima nota siempre estará al alcance.',
    workspace_overview: 'Vista general del espacio',
    dashboard_hero: 'Crea notas una vez y luego traduce, resume, crea cuestionarios, escucha y colabora desde la misma fuente.',
    new_note: 'Nueva nota',
    open_group_room: 'Abrir sala de grupo',
    habit_tracker: 'Seguimiento de hábito',
    your_momentum: 'Tu impulso',
    day_streak: 'días seguidos',
    logins: 'Ingresos',
    times_you_have_shown_up: 'Veces que te has presentado',
    streak: 'Racha',
    consecutive_active_days: 'Días activos consecutivos',
    recent_login_days: 'Días recientes de ingreso',
    login_rhythm_empty: 'Tu ritmo de acceso aparecerá aquí después de tu próximo inicio de sesión.',
    inspiration: 'Inspiración',
    recent_notes: 'Notas recientes',
    recent_notes_copy: 'Abre una nota para editarla, estudiarla o compartirla.',
    view_all: 'Ver todo',
    loading_notes: 'Cargando notas...',
    manage_notes_copy: 'Gestiona archivos importados, notas escritas y material de estudio en un solo lugar.',
    delete_selected: 'Eliminar seleccionadas',
    select_notes: 'Seleccionar notas',
    done: 'Listo',
    move_to_folder: 'Mover a carpeta',
    move_to_notes: 'Mover a notas',
    folders: 'Carpetas',
    folder_manage: 'Gestionar carpetas',
    new_folder_name: 'Nombre de la nueva carpeta',
    create_folder: 'Crear carpeta',
    open: 'Abrir',
    move_selected_here: 'Mover seleccionadas aquí',
    delete_folder: 'Eliminar carpeta',
    no_folders_yet: 'Aún no hay carpetas. Crea una para organizar tus notas aparte de la sección principal.',
    edit_your_note: 'Edita tu nota y luego abre el modo de resumen o cuestionario.',
    untitled_note: 'Nota sin título',
    edit_note_title: 'Editar título de la nota',
    save_note: 'Guardar nota',
    saving: 'Guardando...',
    more_note_actions: 'Más acciones de nota',
    delete: 'Eliminar',
    settings_copy: 'Administra tu idioma predeterminado, voz y preferencias del perfil.',
    preferred_voice: 'Voz preferida',
    use_app_default_voice: 'Usar la voz predeterminada de la app',
    ui_theme: 'Tema de la interfaz',
    system: 'sistema',
    light: 'claro',
    dark: 'oscuro',
    save_settings: 'Guardar configuración',
    summary_copy: 'Guarda tus notas resumidas en un espacio tranquilo para revisarlas fácilmente.',
    summarize_a_note: 'Resumir una nota',
    show_all_summaries: 'Mostrar todos los resúmenes',
    summarized_from: 'Resumido de',
    no_summaries_yet: 'Aún no hay resúmenes. Usa el botón más para elegir una nota y resumirla aquí.',
    pick_or_create_summary: 'Elige o crea un resumen para ver el contenido completo aquí.',
    already_summarized: 'Ya resumida',
  },
  fr: {
    app_name: 'AI Notes',
    tagline: 'Étudiez plus intelligemment, ensemble',
    dashboard: 'Tableau de bord',
    my_notes: 'Mes notes',
    summary: 'Résumé',
    quiz: 'Quiz',
    groups: 'Groupes',
    settings: 'Paramètres',
    sign_out: 'Se déconnecter',
    workspace: 'Espace de travail',
    default_study_language: "Langue d'étude par défaut",
    loading_workspace: 'Chargement de votre espace de travail...',
    focus_mode: 'Mode focus',
    focus_mode_copy: 'Les résumés, quiz, audio et la collaboration en direct sont maintenant connectés à votre backend.',
    ready_to_study: 'Prêt à étudier',
    student: 'Étudiant',
    full_name: 'Nom complet',
    email: 'E-mail',
    password: 'Mot de passe',
    loading: 'Chargement...',
    create_note: 'Créer une note',
    create_a_note: 'Créer une note',
    note_name: 'Nom de la note',
    name_your_note: 'Donnez un nom à votre note',
    creating: 'Création...',
    cancel: 'Annuler',
    content: 'Contenu',
    write_your_study_notes_here: 'Écrivez vos notes ici...',
    import_note: 'Importer une note',
    import_note_copy: 'Collez du texte ou importez un fichier `.txt`, `.pdf` ou `.docx`.',
    optional_title: 'Titre facultatif',
    paste_typed_notes_here: 'Collez vos notes ici...',
    importing: 'Importation...',
    import_into_notes: 'Importer dans les notes',
    create_a_new_note: 'Créer une nouvelle note',
    create_note_tile_copy: 'Commencez une nouvelle idée ici. Votre prochaine note reste toujours à portée de main.',
    workspace_overview: "Vue d'ensemble",
    dashboard_hero: 'Créez des notes une seule fois, puis traduisez, résumez, quizzez, écoutez et collaborez à partir de la même source.',
    new_note: 'Nouvelle note',
    open_group_room: 'Ouvrir la salle de groupe',
    habit_tracker: "Suivi d'habitude",
    your_momentum: 'Votre élan',
    day_streak: 'jours de suite',
    logins: 'Connexions',
    times_you_have_shown_up: 'Nombre de présences',
    streak: 'Série',
    consecutive_active_days: 'Jours actifs consécutifs',
    recent_login_days: 'Jours de connexion récents',
    login_rhythm_empty: 'Votre rythme de connexion apparaîtra ici après votre prochaine connexion.',
    inspiration: 'Inspiration',
    recent_notes: 'Notes récentes',
    recent_notes_copy: 'Ouvrez une note pour la modifier, l’étudier ou la partager.',
    view_all: 'Voir tout',
    loading_notes: 'Chargement des notes...',
    manage_notes_copy: 'Gérez les fichiers importés, les notes écrites et le matériel d’étude au même endroit.',
    delete_selected: 'Supprimer la sélection',
    select_notes: 'Sélectionner des notes',
    done: 'Terminé',
    move_to_folder: 'Déplacer vers un dossier',
    move_to_notes: 'Déplacer vers les notes',
    folders: 'Dossiers',
    folder_manage: 'Gérer les dossiers',
    new_folder_name: 'Nom du nouveau dossier',
    create_folder: 'Créer un dossier',
    open: 'Ouvrir',
    move_selected_here: 'Déplacer ici',
    delete_folder: 'Supprimer le dossier',
    no_folders_yet: "Aucun dossier pour le moment. Créez-en un pour organiser vos notes à part.",
    edit_your_note: 'Modifiez votre note, puis ouvrez le mode résumé ou quiz.',
    untitled_note: 'Note sans titre',
    edit_note_title: 'Modifier le titre de la note',
    save_note: 'Enregistrer la note',
    saving: 'Enregistrement...',
    more_note_actions: 'Plus d’actions',
    delete: 'Supprimer',
    settings_copy: 'Gérez votre langue par défaut, votre voix et les préférences du profil.',
    preferred_voice: 'Voix préférée',
    use_app_default_voice: "Utiliser la voix par défaut de l'application",
    ui_theme: "Thème de l'interface",
    system: 'système',
    light: 'clair',
    dark: 'sombre',
    save_settings: 'Enregistrer les paramètres',
    summary_copy: 'Gardez vos notes résumées dans un espace calme pour les revoir facilement.',
    summarize_a_note: 'Résumer une note',
    show_all_summaries: 'Afficher tous les résumés',
    summarized_from: 'Résumée depuis',
    no_summaries_yet: "Pas encore de résumés. Utilisez le bouton plus pour choisir une note et la résumer ici.",
    pick_or_create_summary: 'Choisissez ou créez un résumé pour voir le contenu complet ici.',
    already_summarized: 'Déjà résumée',
  },
  de: {
    app_name: 'AI Notes',
    tagline: 'Gemeinsam smarter lernen',
    dashboard: 'Übersicht',
    my_notes: 'Meine Notizen',
    summary: 'Zusammenfassung',
    quiz: 'Quiz',
    groups: 'Gruppen',
    settings: 'Einstellungen',
    sign_out: 'Abmelden',
    workspace: 'Arbeitsbereich',
    default_study_language: 'Standard-Lernsprache',
    loading_workspace: 'Dein Arbeitsbereich wird geladen...',
    focus_mode: 'Fokusmodus',
    focus_mode_copy: 'Zusammenfassungen, Quizze, Audio und Live-Zusammenarbeit sind jetzt mit deinem Backend verbunden.',
    ready_to_study: 'Bereit zum Lernen',
    student: 'Student',
    full_name: 'Vollständiger Name',
    email: 'E-Mail',
    password: 'Passwort',
    loading: 'Lädt...',
    create_note: 'Notiz erstellen',
    create_a_note: 'Eine Notiz erstellen',
    note_name: 'Notizname',
    name_your_note: 'Gib deiner Notiz einen Namen',
    creating: 'Wird erstellt...',
    cancel: 'Abbrechen',
    content: 'Inhalt',
    write_your_study_notes_here: 'Schreibe hier deine Lernnotizen...',
    import_note: 'Notiz importieren',
    import_note_copy: 'Text einfügen oder eine `.txt`-, `.pdf`- oder `.docx`-Datei hochladen.',
    optional_title: 'Optionaler Titel',
    paste_typed_notes_here: 'Geschriebene Notizen hier einfügen...',
    importing: 'Importiere...',
    import_into_notes: 'In Notizen importieren',
    create_a_new_note: 'Neue Notiz erstellen',
    create_note_tile_copy: 'Starte hier eine neue Idee. Deine nächste Notiz ist immer in Reichweite.',
    workspace_overview: 'Arbeitsbereichsübersicht',
    dashboard_hero: 'Erstelle Notizen einmal und übersetze, fasse zusammen, quizze, höre an und arbeite gemeinsam mit derselben Quelle.',
    new_note: 'Neue Notiz',
    open_group_room: 'Gruppenraum öffnen',
    habit_tracker: 'Gewohnheitstracker',
    your_momentum: 'Dein Schwung',
    day_streak: 'Tage in Folge',
    logins: 'Anmeldungen',
    times_you_have_shown_up: 'Anzahl deiner Besuche',
    streak: 'Serie',
    consecutive_active_days: 'Aufeinanderfolgende aktive Tage',
    recent_login_days: 'Letzte Anmeldetage',
    login_rhythm_empty: 'Dein Anmelderhythmus erscheint hier nach deiner nächsten Anmeldung.',
    inspiration: 'Inspiration',
    recent_notes: 'Aktuelle Notizen',
    recent_notes_copy: 'Öffne eine Notiz, um sie zu bearbeiten, zu lernen oder zu teilen.',
    view_all: 'Alle anzeigen',
    loading_notes: 'Notizen werden geladen...',
    manage_notes_copy: 'Verwalte importierte Dateien, geschriebene Notizen und Lernmaterial an einem Ort.',
    delete_selected: 'Ausgewählte löschen',
    select_notes: 'Notizen auswählen',
    done: 'Fertig',
    move_to_folder: 'In Ordner verschieben',
    move_to_notes: 'Zu Notizen verschieben',
    folders: 'Ordner',
    folder_manage: 'Ordner verwalten',
    new_folder_name: 'Neuer Ordnername',
    create_folder: 'Ordner erstellen',
    open: 'Öffnen',
    move_selected_here: 'Ausgewählte hierher verschieben',
    delete_folder: 'Ordner löschen',
    no_folders_yet: 'Noch keine Ordner. Erstelle einen, um deine Notizen besser zu organisieren.',
    edit_your_note: 'Bearbeite deine Notiz und öffne dann den Zusammenfassungs- oder Quizmodus.',
    untitled_note: 'Unbenannte Notiz',
    edit_note_title: 'Notiztitel bearbeiten',
    save_note: 'Notiz speichern',
    saving: 'Speichert...',
    more_note_actions: 'Weitere Aktionen',
    delete: 'Löschen',
    settings_copy: 'Verwalte deine Standardsprache, Stimme und Profileinstellungen.',
    preferred_voice: 'Bevorzugte Stimme',
    use_app_default_voice: 'Standardstimme der App verwenden',
    ui_theme: 'Oberflächendesign',
    system: 'system',
    light: 'hell',
    dark: 'dunkel',
    save_settings: 'Einstellungen speichern',
    summary_copy: 'Behalte deine zusammengefassten Notizen in einem ruhigen Bereich, damit du sie leicht wiederfinden kannst.',
    summarize_a_note: 'Eine Notiz zusammenfassen',
    show_all_summaries: 'Alle Zusammenfassungen anzeigen',
    summarized_from: 'Zusammengefasst aus',
    no_summaries_yet: 'Noch keine Zusammenfassungen. Nutze das Plus, um hier eine Notiz auszuwählen und zusammenzufassen.',
    pick_or_create_summary: 'Wähle oder erstelle eine Zusammenfassung, um hier den vollständigen Inhalt zu sehen.',
    already_summarized: 'Bereits zusammengefasst',
  },
  pt: {
    app_name: 'AI Notes',
    tagline: 'Estude melhor, em conjunto',
    dashboard: 'Painel',
    my_notes: 'Minhas notas',
    summary: 'Resumo',
    quiz: 'Quiz',
    groups: 'Grupos',
    settings: 'Configurações',
    sign_out: 'Sair',
    workspace: 'Espaço de trabalho',
    default_study_language: 'Idioma de estudo padrão',
    loading_workspace: 'Carregando seu espaço de trabalho...',
    focus_mode: 'Modo de foco',
    focus_mode_copy: 'Resumos, quizzes, áudio e colaboração ao vivo agora estão conectados ao seu backend.',
    ready_to_study: 'Pronto para estudar',
    student: 'Estudante',
    full_name: 'Nome completo',
    email: 'E-mail',
    password: 'Senha',
    loading: 'Carregando...',
    create_note: 'Criar nota',
    create_a_note: 'Criar uma nota',
    note_name: 'Nome da nota',
    name_your_note: 'Dê um nome à sua nota',
    creating: 'Criando...',
    cancel: 'Cancelar',
    content: 'Conteúdo',
    write_your_study_notes_here: 'Escreva suas notas de estudo aqui...',
    import_note: 'Importar nota',
    import_note_copy: 'Cole texto ou envie um arquivo `.txt`, `.pdf` ou `.docx`.',
    optional_title: 'Título opcional',
    paste_typed_notes_here: 'Cole suas notas aqui...',
    importing: 'Importando...',
    import_into_notes: 'Importar para notas',
    create_a_new_note: 'Criar uma nova nota',
    create_note_tile_copy: 'Comece uma ideia nova aqui. Sua próxima nota está sempre por perto.',
    workspace_overview: 'Visão geral do espaço',
    dashboard_hero: 'Crie notas uma vez e depois traduza, resuma, gere quiz, ouça e colabore a partir da mesma fonte.',
    new_note: 'Nova nota',
    open_group_room: 'Abrir sala em grupo',
    habit_tracker: 'Rastreador de hábito',
    your_momentum: 'Seu ritmo',
    day_streak: 'dias seguidos',
    logins: 'Entradas',
    times_you_have_shown_up: 'Vezes em que você apareceu',
    streak: 'Sequência',
    consecutive_active_days: 'Dias ativos consecutivos',
    recent_login_days: 'Dias recentes de entrada',
    login_rhythm_empty: 'Seu ritmo de entrada aparecerá aqui após o próximo login.',
    inspiration: 'Inspiração',
    recent_notes: 'Notas recentes',
    recent_notes_copy: 'Abra uma nota para editar, estudar ou compartilhar.',
    view_all: 'Ver tudo',
    loading_notes: 'Carregando notas...',
    manage_notes_copy: 'Gerencie arquivos importados, notas digitadas e material de estudo em um só lugar.',
    delete_selected: 'Excluir selecionadas',
    select_notes: 'Selecionar notas',
    done: 'Concluído',
    move_to_folder: 'Mover para pasta',
    move_to_notes: 'Mover para notas',
    folders: 'Pastas',
    folder_manage: 'Gerenciar pastas',
    new_folder_name: 'Nome da nova pasta',
    create_folder: 'Criar pasta',
    open: 'Abrir',
    move_selected_here: 'Mover selecionadas para cá',
    delete_folder: 'Excluir pasta',
    no_folders_yet: 'Ainda não há pastas. Crie uma para organizar suas notas separadamente.',
    edit_your_note: 'Edite sua nota e depois abra o modo de resumo ou quiz.',
    untitled_note: 'Nota sem título',
    edit_note_title: 'Editar título da nota',
    save_note: 'Salvar nota',
    saving: 'Salvando...',
    more_note_actions: 'Mais ações da nota',
    delete: 'Excluir',
    settings_copy: 'Gerencie seu idioma padrão, voz e preferências do perfil.',
    preferred_voice: 'Voz preferida',
    use_app_default_voice: 'Usar a voz padrão do app',
    ui_theme: 'Tema da interface',
    system: 'sistema',
    light: 'claro',
    dark: 'escuro',
    save_settings: 'Salvar configurações',
    summary_copy: 'Mantenha suas notas resumidas em um espaço calmo para revisá-las com facilidade.',
    summarize_a_note: 'Resumir uma nota',
    show_all_summaries: 'Mostrar todos os resumos',
    summarized_from: 'Resumido de',
    no_summaries_yet: 'Ainda não há resumos. Use o botão de mais para escolher uma nota e resumi-la aqui.',
    pick_or_create_summary: 'Escolha ou crie um resumo para ver o conteúdo completo aqui.',
    already_summarized: 'Já resumida',
  },
  ar: {
    app_name: 'AI Notes',
    tagline: 'ادرس بذكاء أكثر، معًا',
    dashboard: 'لوحة التحكم',
    my_notes: 'ملاحظاتي',
    summary: 'الملخص',
    quiz: 'الاختبار',
    groups: 'المجموعات',
    settings: 'الإعدادات',
    sign_out: 'تسجيل الخروج',
    workspace: 'مساحة العمل',
    default_study_language: 'لغة الدراسة الافتراضية',
    loading_workspace: 'يتم تحميل مساحة العمل...',
    focus_mode: 'وضع التركيز',
    focus_mode_copy: 'الملخصات والاختبارات والصوت والتعاون المباشر كلها متصلة الآن بالخلفية الخاصة بك.',
    ready_to_study: 'جاهز للدراسة',
    student: 'طالب',
    full_name: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    loading: 'جارٍ التحميل...',
    create_note: 'إنشاء ملاحظة',
    create_a_note: 'إنشاء ملاحظة',
    note_name: 'اسم الملاحظة',
    name_your_note: 'سمِّ ملاحظتك',
    creating: 'جارٍ الإنشاء...',
    cancel: 'إلغاء',
    content: 'المحتوى',
    write_your_study_notes_here: 'اكتب ملاحظاتك الدراسية هنا...',
    import_note: 'استيراد ملاحظة',
    import_note_copy: 'ألصق نصًا أو ارفع ملفًا بصيغة `.txt` أو `.pdf` أو `.docx`.',
    optional_title: 'عنوان اختياري',
    paste_typed_notes_here: 'ألصق ملاحظاتك هنا...',
    importing: 'جارٍ الاستيراد...',
    import_into_notes: 'استيراد إلى الملاحظات',
    create_a_new_note: 'إنشاء ملاحظة جديدة',
    create_note_tile_copy: 'ابدأ فكرة جديدة هنا. ملاحظتك التالية تبقى دائمًا في متناولك.',
    workspace_overview: 'نظرة عامة على مساحة العمل',
    dashboard_hero: 'أنشئ الملاحظات مرة واحدة ثم ترجمها ولخصها وحولها إلى اختبارات واستمع إليها وتعاون من المصدر نفسه.',
    new_note: 'ملاحظة جديدة',
    open_group_room: 'فتح غرفة المجموعة',
    habit_tracker: 'متتبع العادة',
    your_momentum: 'زخمك',
    day_streak: 'أيام متتالية',
    logins: 'مرات الدخول',
    times_you_have_shown_up: 'عدد المرات التي حضرت فيها',
    streak: 'سلسلة',
    consecutive_active_days: 'أيام النشاط المتتالية',
    recent_login_days: 'أيام الدخول الأخيرة',
    login_rhythm_empty: 'سيظهر نمط دخولك هنا بعد تسجيل الدخول التالي.',
    inspiration: 'إلهام',
    recent_notes: 'الملاحظات الحديثة',
    recent_notes_copy: 'افتح ملاحظة لتعديلها أو دراستها أو مشاركتها.',
    view_all: 'عرض الكل',
    loading_notes: 'جارٍ تحميل الملاحظات...',
    manage_notes_copy: 'أدر الملفات المستوردة والملاحظات المكتوبة ومواد الدراسة في مكان واحد.',
    delete_selected: 'حذف المحدد',
    select_notes: 'تحديد الملاحظات',
    done: 'تم',
    move_to_folder: 'نقل إلى مجلد',
    move_to_notes: 'إرجاع إلى الملاحظات',
    folders: 'المجلدات',
    folder_manage: 'إدارة المجلدات',
    new_folder_name: 'اسم المجلد الجديد',
    create_folder: 'إنشاء مجلد',
    open: 'فتح',
    move_selected_here: 'نقل المحدد إلى هنا',
    delete_folder: 'حذف المجلد',
    no_folders_yet: 'لا توجد مجلدات بعد. أنشئ واحدًا لتنظيم ملاحظاتك بشكل أفضل.',
    edit_your_note: 'عدّل ملاحظتك ثم افتح وضع الملخص أو الاختبار.',
    untitled_note: 'ملاحظة بلا عنوان',
    edit_note_title: 'تعديل عنوان الملاحظة',
    save_note: 'حفظ الملاحظة',
    saving: 'جارٍ الحفظ...',
    more_note_actions: 'المزيد من الإجراءات',
    delete: 'حذف',
    settings_copy: 'أدر لغة التطبيق الافتراضية والصوت وتفضيلات الملف الشخصي.',
    preferred_voice: 'الصوت المفضل',
    use_app_default_voice: 'استخدام الصوت الافتراضي للتطبيق',
    ui_theme: 'مظهر الواجهة',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    save_settings: 'حفظ الإعدادات',
    summary_copy: 'احتفظ بملخصاتك في مساحة هادئة لتعود إليها بسهولة.',
    summarize_a_note: 'تلخيص ملاحظة',
    show_all_summaries: 'عرض كل الملخصات',
    summarized_from: 'تم تلخيصه من',
    no_summaries_yet: 'لا توجد ملخصات بعد. استخدم زر الإضافة لاختيار ملاحظة وتلخيصها هنا.',
    pick_or_create_summary: 'اختر أو أنشئ ملخصًا لرؤية المحتوى الكامل هنا.',
    already_summarized: 'تم تلخيصها بالفعل',
  },
  yo: {
    app_name: 'AI Notes',
    tagline: 'Kawe ni ọgbọn diẹ sii, papọ',
    dashboard: 'Pẹpẹ iṣakoso',
    my_notes: 'Àwọn àkíyèsí mi',
    summary: 'Akopọ',
    quiz: 'Ìdánwò',
    groups: 'Àwọn ẹgbẹ́',
    settings: 'Ètò',
    sign_out: 'Jade',
    workspace: 'Agbègbè iṣẹ́',
    default_study_language: 'Èdè ìkẹ́kọ̀ọ́ àkọ́kọ́',
    loading_workspace: 'Ń gbé agbègbè iṣẹ́ rẹ kalẹ...',
    focus_mode: 'Ipo ìfojúsùn',
    focus_mode_copy: 'Akopọ, ìdánwò, ohun àti ìfọwọ́sowọpọ̀ láàyè ti sopọ mọ backend rẹ báyìí.',
    ready_to_study: 'Ṣetan láti kawe',
    student: 'Akẹ́kọ̀ọ́',
    full_name: 'Orúkọ kikun',
    email: 'Íméèlì',
    password: 'Ọ̀rọ̀ aṣínà',
    loading: 'Ń gbé kalẹ...',
    create_note: 'Ṣẹda àkíyèsí',
    create_a_note: 'Ṣẹda àkíyèsí kan',
    note_name: 'Orúkọ àkíyèsí',
    name_your_note: 'Fi orúkọ sí àkíyèsí rẹ',
    creating: 'Ń ṣẹda...',
    cancel: 'Fagilé',
    content: 'Àkóónú',
    write_your_study_notes_here: 'Kọ àwọn àkíyèsí ìkẹ́kọ̀ọ́ rẹ síbí...',
    import_note: 'Gbe àkíyèsí wọlé',
    import_note_copy: 'Lẹ̀mọ̀ọ́kọ̀ọ̀kan kọ tàbí gbe fáìlì `.txt`, `.pdf`, tàbí `.docx` wọlé.',
    optional_title: 'Akọlé àṣàyàn',
    paste_typed_notes_here: 'Lẹ́ àkíyèsí tí a tẹ síbí...',
    importing: 'Ń gbe wọlé...',
    import_into_notes: 'Gbe wọlé sí àwọn àkíyèsí',
    create_a_new_note: 'Ṣẹda àkíyèsí tuntun',
    create_note_tile_copy: 'Bẹrẹ ero tuntun níbí. Àkíyèsí rẹ tó kàn máa wà nítòsí rẹ nígbà gbogbo.',
    workspace_overview: 'Akopọ agbègbè iṣẹ́',
    dashboard_hero: 'Ṣẹda àkíyèsí lẹ́ẹ̀kan, lẹ́yìn náà túmọ̀, ṣe akopọ, dá ìdánwò, gbọ́ ohun, kí o sì fọwọ́sowọpọ̀ láti orísun kan náà.',
    new_note: 'Àkíyèsí tuntun',
    open_group_room: 'Ṣí yàrá ẹgbẹ́',
    habit_tracker: 'Olùtọ́pa ìṣe',
    your_momentum: 'Ìlọsíwájú rẹ',
    day_streak: 'ọjọ́ lẹ́sẹ̀sẹ̀',
    logins: 'Ìwọlé',
    times_you_have_shown_up: 'Iye ìgbà tí o ti farahàn',
    streak: 'Ìtẹ̀síwájú',
    consecutive_active_days: 'Àwọn ọjọ́ ìṣiṣẹ́ lẹ́sẹ̀sẹ̀',
    recent_login_days: 'Àwọn ọjọ́ ìwọlé tó ṣẹ̀ṣẹ̀',
    login_rhythm_empty: 'Ìlànà ìwọlé rẹ yóò hàn níbí lẹ́yìn ìwọlé tó tẹ̀le.',
    inspiration: 'Ìmísí',
    recent_notes: 'Àwọn àkíyèsí tuntun',
    recent_notes_copy: 'Ṣí àkíyèsí kan láti ṣàtúnṣe, kawe, tàbí pín un.',
    view_all: 'Wo gbogbo rẹ',
    loading_notes: 'Ń gbé àwọn àkíyèsí kalẹ...',
    manage_notes_copy: 'Ṣakoso àwọn fáìlì tí a wọlé, àkíyèsí tí a kọ, àti ohun èlò ìkẹ́kọ̀ọ́ ní ibi kan.',
    delete_selected: 'Pa àwọn tí a yan',
    select_notes: 'Yan àwọn àkíyèsí',
    done: 'Parí',
    move_to_folder: 'Gbé lọ sí folda',
    move_to_notes: 'Gbé padà sí àkíyèsí',
    folders: 'Àwọn folda',
    folder_manage: 'Ṣakoso àwọn folda',
    new_folder_name: 'Orúkọ folda tuntun',
    create_folder: 'Ṣẹda folda',
    open: 'Ṣí',
    move_selected_here: 'Gbé àwọn tí a yan wá síbí',
    delete_folder: 'Pa folda',
    no_folders_yet: 'Kò tíì sí folda kankan. Ṣẹda ọkan láti ṣètò àwọn àkíyèsí rẹ.',
    edit_your_note: 'Ṣàtúnṣe àkíyèsí rẹ, lẹ́yìn náà ṣí ipo akopọ tàbí ìdánwò.',
    untitled_note: 'Àkíyèsí láìsí akọlé',
    edit_note_title: 'Ṣàtúnṣe akọlé àkíyèsí',
    save_note: 'Fipamọ àkíyèsí',
    saving: 'Ń fipamọ...',
    more_note_actions: 'Ìṣe àfikún',
    delete: 'Pa á',
    settings_copy: 'Ṣakoso èdè àkọ́kọ́ rẹ, ohùn àti àwọn àṣàyàn profaili.',
    preferred_voice: 'Ohùn tí o fẹ́',
    use_app_default_voice: 'Lo ohùn àkọ́kọ́ app',
    ui_theme: 'Àwọ̀ ojú-òpó',
    system: 'ẹ̀rọ',
    light: 'fẹẹrẹfẹẹrẹ',
    dark: 'dúdú',
    save_settings: 'Fipamọ ètò',
    summary_copy: 'Pa àwọn àkótán rẹ mọ́ sí ibi tó dakẹ́ kí o lè tún wo wọn rọrùn.',
    summarize_a_note: 'Ṣe akopọ àkíyèsí kan',
    show_all_summaries: 'Fi gbogbo akopọ hàn',
    summarized_from: 'A ṣe akopọ láti',
    no_summaries_yet: 'Kò tíì sí akopọ. Lo bọ́tìnì plus láti yan àkíyèsí kan kí o ṣe akopọ rẹ níbí.',
    pick_or_create_summary: 'Yan tàbí ṣẹda akopọ kan láti wo àkóónú kikun níbí.',
    already_summarized: 'A ti ṣe akopọ rẹ tẹ́lẹ̀',
  },
}

const fallbackLanguage = 'en'

export const getAppLanguage = (preferredLanguage) => {
  if (!preferredLanguage) {
    return fallbackLanguage
  }
  const normalized = preferredLanguage.toLowerCase()
  return copy[normalized] ? normalized : fallbackLanguage
}

export const createTranslator = (preferredLanguage) => {
  const language = getAppLanguage(preferredLanguage)
  return (key, replacements = {}) => {
    const template = copy[language]?.[key] ?? copy[fallbackLanguage][key] ?? key
    return Object.entries(replacements).reduce(
      (result, [token, value]) => result.replaceAll(`{${token}}`, String(value)),
      template,
    )
  }
}

export const formatLocalizedDate = (value, preferredLanguage, options) => {
  const locale = getAppLanguage(preferredLanguage)
  try {
    return new Date(value).toLocaleDateString(locale, options)
  } catch {
    return new Date(value).toLocaleDateString(fallbackLanguage, options)
  }
}
